---
title: Task
---
classDiagram
    class Task
    Task : +int id
    Task : +String title
    Task : +String description
    Task : +String img
    Task : +Date   startDate
    Task : +Date   endDate
